camaraproject/EdgeCloud

MAINTAINERS.MD

Add TIM Contributors

---

api_proposal/APIproposal_Traffic Influence_TIM.md
api_proposal/Userstory_Traffic Influence_TIM.md
code/API_definitions/TrafficInfluencev0.1.yaml

TI API proposal to be merged on the main branch

Traffic Influence API proposal

---

documentation/SupportingDocuments/describing and harmonising the Edge APIs

First draft for initial review. 
Note I have called the third API 'GSMA and MobiledgeXR' API for now but please rename it if it has another name
TODO:
I need to add the flows for each API

Create describing and harmonising the Edge APIs

---

code/API_definitions/App.yaml

Openapi spec for App definition management. These APIs are a subset of the full EdgeXR Edge Cloud APIs so refer to some definitions not present here. This fixes #29.
Unfortunately I do have permissions to create a new branch in camaraproject/EdgeCloud, so I cannot set my merge target to an EdgeXR-specific branch. For now, like other PRs, it is targeting the main branch but will not be pushed. It is just for reference only.

EdgeXR App Apis

---

code/API_definitions/app-client.yaml
code/API_definitions/session.yaml

EdgeXR Edge Cloud Application discovery and session APIs. These are generated from protobuffers definitions so may have some artifacts related to that. This fixes #28.
As noted on the other PR, I don't have perms to create an EdgeXR specific branch to target so this targets main, but is intended for reference only, not actually for merging.

EdgeXR App session and discovery APIs

---

documentation/Contributions/edge_terminology.md

- fixed typos
- made table alphabetical
- made glossary terms bold
- added some missing definitions

Updates following feedback from Orange

---

README.md

Included the Traffic Influence feature in the Edge Cloud API Family description

Update REARDME.md to include Traffic Influnce

---

documentation/SupportingDocuments/describing and harmonising the Edge APIs.md

Also added the sequence diagram for Simple Edge Discovery

Merged GSMA intents

---

code/API_definitions/MEC exposure and experience management.yaml

updates based on issue #38 
unused components as mentioned in the issue have been removed. 
removed commented sections which are not required.
Also updates have been made to use camel case through out the spec for all input and output data.

Update MEC exposure and experience management.yaml

---

code/API_definitions/simple_edge_discovery.yaml

Per API design guidelines - now aligned with MEC Exposure and Experience Management API

Updated to CamelCase

---

api_proposal/Userstory_Rel2_Traffic Influence_TIM.md

This is the use case for release 2 of the Traffic Influence API

Use Case for User Mobility

---

documentation/SupportingDocuments/Harmonisation of APIs/describing and harmonising the Edge APIs.md

Clarified the first scenario and added and additional scenario for Simple Edge Discovery

Update Simple Edge Discovery flows

---

documentation/SupportingDocuments/API_Documentation/Traffic_Influence_API_Readiness_Checklist.md

Status of the TI API v0.9 considering the Readiness Checklist

TI API Readiness Checklist

---

code/API_definitions/Workload Orchestration/README.md

Create README.md for Workload Orchestration

---

code/API_definitions/Resource Management/README.MD

Create README.MD for Resource Management

---

README.md

Modified Readme to add Slack channel link

Added slack channel link

---

code/Test_definitions/Traffic_Influence_Test.feature

Added support to User Mobility, providing a new test case for a Device moving to another geographical area.

Test file updated for TI API v0.9.2

---

CODEOWNERS

Added Nicola Cadenelli from NearbyComputing

Update CODEOWNERS to add Nicola Cadenelli and Jon Gansley

---

code/API_definitions/Discovery/simple_edge_discovery.yaml

Identified and fixed a typo and issues with punctuation.

fixed typos and punctuation

---

documentation/SupportingDocuments/Harmonisation of APIs/describing and harmonising the Edge APIs.md

Corrected text to confirm that EDS can be called from an application server, or by an application client on a device.

Update describing and harmonising the Edge APIs.md

---

code/Test_definitions/Edgecloud_LCM_Test.feature

First version of Gherkin test feature file for EdgeCloud_LCM including at lis one test with response ok and one test with response nok for all existing POST,GET,DELETE methods in version 0.9.2 (https://github.com/camaraproject/EdgeCloud/pull/208)

Gherkin Test feature file for EdgeCloud_LCM

---

code/API_definitions/Traffic_Influence.yaml

* cleanup
This PR includes API terminology alignment with Edge Cloud Family, Consent Management and it is choerent with the new Edge Cloud folder structure

TI API Rel 0.9.3 new Edge Cloud folder structure

---

documentation/API_documentation/Traffic_Influence_API_Readiness_Checklist.md

**What type of PR is this?**
updating the readiness checklist according to the new format define in Release Management (https://github.com/camaraproject/ReleaseManagement/blob/25400e8f484dbb6e53a7dcc21d3a709b6cc2b686/documentation/API-Readiness-Checklist.md)
documentation
**What this PR does / why we need it:**
To be coherent with the readiness checklist
**Which issue(s) this PR fixes:**
https://github.com/camaraproject/EdgeCloud/issues/242

TI API new Readiness Checklist

---

MAINTAINERS.MD

* correction
* subproject management
The Github username of Deepak Gunjal in the MAINTAINERS.md was obviously wrong. 
Fixes #na / minor fix

Correction of GitHub username in MAINTAINERS.MD

---

code/API_definitions/Edge-Application-Management.yaml

* bug
Fixes lint errors, found by mega linter in another PR. Not sure how it wasn't detected in the original PR (#280).

EAM API: Fix lint errors

---

code/API_definitions/Application-endpoint-registration.yaml

* correction
Update on the Error codes and fixing the Typos of Application Endpoint Registration API

EAR: Fixing Typo

---

README.md

* subproject management
Adding the links to SimpleEdgeDiscovery and TrafficInfluece child repositories to the README.md file. To facilitate the connection to the child repositories of the APIs.
https://github.com/camaraproject/EdgeCloud/issues/341

Links to child Repos on README

---

code/API_definitions/Application_Endpoint_Discovery_API.yaml

This PR is changes API to have Device schema as per community guidelines. It also has API changes for using POST request method instead of GET method for standardisation.
issue #336

AED enhancements

---

code/Test_definitions/Edgecloud_LCM_Test.feature
code/Test_definitions/Traffic_Influence_Test.feature

* correction
This PR corrects typos and grammar mistakes in Gherkin feature files to improve documentation clarity and maintain consistency in test specifications. This ensures better readability of test scenarios and alignment with CAMARA API documentation standards.
N/A (No existing issue created for these typo fixes)
- Changes are limited to non-functional text corrections
- All typos were identified in scenario descriptions and response documentation
- "valorised" was consistently changed to "set"/"populated" based on API terminology standards
- No actual code logic or test behavior was modified
```
release-note
None (Documentation-only changes)
```

Fix typos and improve terminology consistency in Gherkin feature files

---

code/API_definitions/Application-endpoint-registration.yaml

* correction
Fixes #
```
release-note
```
```
docs
```

Modified 4 to 5 operations in Application-endpoint-registration.yaml

---

code/API_definitions/Application-endpoint-registration.yaml

Reverts camaraproject/EdgeCloud#343

Revert "Modified 4 to 5 operations in Application-endpoint-registration.yaml"

---

code/API_definitions/Application_Endpoint_Discovery_API.yaml

Reverts camaraproject/EdgeCloud#337
reverting the changes are the changes has linting errors which were not detected due to spectral files missing. These changes have to be re committed after linting errors are address as part of PR #346

Revert "AED enhancements"

---

code/API_definitions/Application_Endpoint_Discovery_API.yaml

It resolves the lint issues from PR 337
There are existing lint issues that are preventing the new PR to pass the megalinter check.

resolved conflicts and fixed lint issues for AED enhancements

---

.github/workflows/megalinter.yml
.spectral.yml
.yamllint.yaml

* subproject management
.spectral.yml is outdated
.yamllint.yaml is not present, hence the default config is used for yamllint 
The problem was discovered when #337 and #321 were analysed
```
Megalinter config files updated
```

Linting config update

---

code/API_definitions/Application_Endpoint_Discovery_API.yaml

This PR provides changes in AED API spec including some corrections, minor typo errors, and enhancements proposed.
* #366 - updated Device object schema according to Commonalities definition
* #367 - updated Errors and x-correlator parameter/header to Commonalities definition
* #368 - update spec to use EdgeCloudZone object as defined by EAM API
* #362 - Updated 401 error removing AUTHENTICATION required (https://github.com/camaraproject/Commonalities/pull/429 as part of Commonalities 0.6 updates for Fall25)
* Minor typo error on ResourceApplicationEndpoint object
* Added some examples to the API spec
* Added reference to commonalities 0.5 spec (to be updated to 0.6 in later PR)
* Updated operationId to getClosestAppEndpoint which defines better the intent of the operation

Application Endpoint Discovery API - Update specification according to issues created

---

.gherkin-lintrc
code/API_definitions/Application_Endpoint_Discovery_API.yaml
code/Test_definitions/application-endpoint-discovery.feature
documentation/SupportingDocuments/API_Documentation/User Stories/Application Endpoint Discovery User Story.md

* API updated (spec and documentation) to Commonalities 0.6
** Version updated to 0.6 release
** X-Correlator Format changed (https://github.com/camaraproject/Commonalities/pull/463)
** Removed IDENTIFIER_MISSMATCH error and introduced DeviceResponse object (https://github.com/camaraproject/Commonalities/pull/455)
** Not Documented Error Responses info.description section added as per last agreed text by Commonalities (https://github.com/camaraproject/Commonalities/pull/457)
* Minor updates on User Story, Test feature and API spec docs before Fall25 release
** Added .gherkin-lintrc file for Test Feature linting (NOTE: added only for local testing purposes so it is prepared when we migrate the code to EAD repo. The gitActions pipeline won't trigger this on EdgeCloud repository).
** Test …

Update EAD API to Commonalities 0.6 and final review of API spec, User Story and Test feature spec before Fall25 meta-release
