camaraproject/EdgeCloud

code/API_definitions/edgexr-nb-openapi.yaml
This adds the full EdgeXR platform North Bound (user facing) APIs. Previously, the App.yaml only provided App definition APIs. This openapi spec includes those App APIs plus all our other APIs for managing instances, cloudlets, policies, resources, etc.
=> Add full EdgeXR NorthBound APIs

documentation/SupportingDocuments/describing and harmonising the Edge APIs.md
The changes submitted describes the developer or application provider intents enabled by the OPAG/Capgemini proposed APIs on NBI
=> Update describing and harmonising the Edge APIs.md

documentation/SupportingDocuments/edgemodel.md
This is a first draft of creating an ERM to describe the basic entities relevant for the edge cloud APIs. This initial draft is based on https://github.com/camaraproject/EdgeCloud/blob/main/documentation/Contributions/edge_terminology.md but certain conflicts have been notified, most prominently the notion of an "Operator Platform" used in GSMA but not in 5GFF. Therefore this version is considered only as a starting point for further work and iteration to align the logical concepts.
=> Create Edge Model

code/API_definitions/Discovery/simple_edge_discovery.yaml
* Unused parameters removed
* Unused resource types removed
* `filter` parameter added (to future-proof  `GET /mecplatforms` with no filter as a request to read the collection resource)
* URI changed to kebab-case
* OperationId updated to Camel Case
*  Identifiers moved to header for security reasons and aligned withe identifier names in  Device Identifier API and QoD API
* Basepath updated including major version
* Standard error codes added
* Documentation simplified and examples added
* following review: success response made inline
=> Simple EDS API Aligned with commonalities

code/API_definitions/Discovery/simple_edge_discovery.yaml
=> Minor patch (OAS version +documentation correction)

code/API_definitions/Discovery/simple_edge_discovery.yaml
As discussed in #150, this MR updates the `Provider` and `Ern` resource names to be more descriptive.
=> More descriptive resources names in Simple Edge Discovery

code/Test_definitions/Traffic_Influence_Test.feature
Added a user mobility test case to be aligned with the TI API v0.9.2
=> User mobility test - TI API v0.9.2

code/API_definitions/Discovery/README.md
Added mapping of each API to intents
Fixes issue #129
=> Create README.md for Discovery folder with intents

CODEOWNERS
Request to modify current telefonica technical representative in codeowners from Sergio Francisco Ortiz to Javier Loza who is currently contributing with LCM API
=> Update CODEOWNERS substitute Telefonica representative

README.md
Due to be able to record the meetings, we change the meeting´s platform from teams to LFX Zoom.
=> Update README.md to change meeting´s platform

code/API_definitions/Discovery/README.md, code/API_definitions/Discovery/simple_edge_discovery.yaml
Abide with the Megalinter workflow and spelling. **Changes to the API itself need a dedicated PR.**
Current linting is complaining about these two lines that are a regex and I'm not sure how to hard wrap. In any case, we can use equivalent regex that are also shorter. But that's for another PR. 
```yaml
- pattern: "^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$"
- pattern: "^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))$" 
```
None
=> Simple edge discovery: spelling and linting

code/API_definitions/EdgeCloud_LcM.yaml, documentation/SupportingDocuments/API_Documentation/Edge.Cloud.Lifecycle.Management.User.Story.md, documentation/SupportingDocuments/API_Documentation/EdgeCloud_LcM_Documentation.md
Adopted Edge Cloud Zone name. 
Adjusting errors detected in Linter for paths name for /app-instance and duplicated method which has been fixed including Delete method in /app-instance/{appId}. Method /app-instace/{appInstanceId} deleted.
=> EdgeCloud_LcM.yaml v0.9.2 with EdgeCloudZone and first Linter corrections. Documentation and User Story

code/API_definitions/Discovery/simple_edge_discovery.yaml
Changed basepath version to /v1
Changed API version number to 1.0.0
PR to propose Simple Edge Discovery 1.0.0 (ref [minutes of Edge Cloud call 16 April](https://wiki.camaraproject.org/display/CAM/2024-04-16%3A+SP-EDC+Minutes) )
Updates version number to 1.0.0 and basepath to /v1
Linter output for this file in isolation: 
```
kev@MDC0D157A lint % spectral lint ../EdgeCloud/code/API_definitions/Discovery/simple_edge_discovery.yaml --verbose --ruleset .spectral.yml > eds_1.txt      
(node:38011) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
kev@MDC0D157A lint % cat eds_1.txt 
Found 68 rules (58 enabled) …
```
=> Simple Edge Discovery 1.0.0

CODEOWNERS, MAINTAINERS.MD
* subproject management
See #260 
Fixes #260 
@FredericFi need to accept the invite into the CAMARA GitHub organisation
=> 260 update and review codeowners and maintainersmd file

code/API_definitions/Application_Endpoint_Discovery_API.yaml
The Application Discovery API extends beyond the capabilities of the
Simple Edge Discovery API by not only locating the nearest Edge Cloud Zone
but also directly linking to the application endpoints within those zones.
This PR covers intent 21.
Fixes #212 
```
release-note
```
```
docs
```
=> Application Endpoint Discovery First Contribution

code/Test_definitions/Traffic_Influence_Test.feature
Improvement of the Test .feature file
Improves the .feature file
https://github.com/camaraproject/EdgeCloud/issues/281
=> TI API: Test file improvement

code/API_definitions/Traffic_Influence.yaml
Resource modification while action is still in progress.
The PR improves the error handling when the API Consumer invokes the TI API for the same Device-AppId if the previous requests are not completed yet.
Resource modification while action is still in progress: https://github.com/camaraproject/EdgeCloud/issues/291
=> TI API: Resource modification

code/API_definitions/Traffic_Influence.yaml
* cleanup
This PR improves the TI API documentation and returned values to help the API Consumer to identify the target of the service data flow (the selected Edge EAS)
- DNS cache: https://github.com/camaraproject/EdgeCloud/issues/293
- Destination EAS IP: https://github.com/camaraproject/EdgeCloud/issues/294
- Documentation improvement: https://github.com/camaraproject/EdgeCloud/issues/309
```
- Documentation modified to add DNS and better explanation on the tasks from the TI API and API Consumer in order to identify the correct target of the service data flow
- added "selected_appInstanceId" as output parameter in the API Notification
```
=> TI API: Rel 0.9.8

code/API_definitions/Edge-Application-Management.yaml
* correction
Adds the missing AppProvider to the AppManifest model.
Fixes #251 
```
Add AppProvider field to AppManifest
```
=> EAM API: Add missing AppProvider

code/API_definitions/Edge-Application-Management.yaml
This adds an API call to list created applications. Currently there is no way to query the existing applications outside of knowing the AppIds of created apps, which requires the client side to maintain a database of AppIds. This is not feasible for web or CLI based clients.
Fixes #
```
release-note
```
```
docs
```
=> EAM API: add list apps api

code/API_definitions/Edge-Application-Management.yaml
Removes appId from the appinstances path. For retrieval, it becomes an optional parameter, allowing a single API call to get appinstances from different Apps. For delete, it is not necessary because appInstanceId is sufficient to identify the instance.
Fixes #299 
```
release-note
```
```
docs
```
=> EAM API: remove appid from appinstance path

code/API_definitions/Edge-Application-Management.yaml
* correction
Change AppManifest version from int to string, to allow version to be in [semver](https://semver.org/) format, i.e. "1.0.1", or like a docker tag, i.e. "latest" or "stable-1.0", or an integer as it was originally. Basically requiring it to an integer is too limiting.
Fixes #
```
change AppManifest version field type from integer to string
```
```
docs
```
=> EAM API: change AppManifest version to string

code/API_definitions/Application-endpoint-registration.yaml
* correction
Added getAllRegisteredApplicationEndpoints API
Updated Error codes, Description
Fixes #
```
release-note
```
```
docs
```
=> AER: Updated Error Codes, Description and added GetAllRegisteredApplicationEndpoints API

code/API_definitions/Application-endpoint-registration.yaml
* correction
Fixes #
```
release-note
```
```
docs
```
=> AER: Fixed Linting issues

code/API_definitions/Edge-Application-Management.yaml
* correction
This removes an unnecessary layer of hierarchy in the GET appinstances response, so it returns an array of objects rather than an array of objects encased in a parent object. This also makes it consistent with GET apps and GET edge-cloud-zones which also return arrays of objects, not arrays of objects inside an object.
```
release-note
- remove enclosing object in GET appinstances response
```
=> EAM API: make GET appinstances response data consistent

code/API_definitions/Edge-Application-Management.yaml
Addresses a comment in #280 regarding the addition of the KubernetesClusterRef, and how users would expect to find it. While the KubernetesClusterRef can be found in the AppInstanceInfo, there may be clusters present without any AppInstances. The only way to see those clusters is via a cluster API to list the clusters.
```
release-note
- add clusters list API
```
=> EAM API: add get clusters api

code/API_definitions/Application-endpoint-registration.yaml
* correction
Fixes #
```
release-note
```
```
docs
```
=> AER: Minor changes. Modified "ApplicationEndpointRequest" to "ApplicationEndpointInfo"

code/API_definitions/Edge-Application-Management.yaml
* correction
Clarifies the behavior of the GET appinstances API if there are no matching instances to return. Implementors may consider returning 404 in this case, but I believe it is more correct to return 200 with an empty list, because:
- 404 is also returned if the URL path is incorrect, which makes it hard to distinguish between no matches vs invalid URL path
- Users (in particular tests) may intentionally be checking for the absence of an instance. Returning 404 in this case complicates verifying the absence of an instance.
=> EAM API: clarify appinstances get behavior

code/API_definitions/Optimal-Edge-Discovery.yaml, code/API_definitions/edge-discovery-service.yaml
* cleanup
* Documentation
This segregates and simplifies edge cloud zone and application endpoint discovery APIs:
- GET edge cloud regions API to fetch edge cloud region id and name required for discovery APIs.
- POST method containing standardised device information schema along with application profile id for edge cloud zone discovery.
- POST method along with device information with application endpoint ids and edge cloud regions for application endpoint discovery.
- added information for access and authorisation token
=> Edge discovery APIs enhancements
